// Generated by CoffeeScript 1.7.1
(function() {
  var InstrumentSound,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InstrumentSound = (function(_super) {
    __extends(InstrumentSound, _super);

    function InstrumentSound() {}

    return InstrumentSound;

  })(App.Sound);

}).call(this);
