// Generated by CoffeeScript 1.7.1
(function() {
  var isNumber;

  isNumber = function(n) {
    if (n instanceof Number) {
      n = n.valueOf();
    }
    return typeof n === "number" && !isNaN(n) && isFinite(n);
  };

  App.Instrument = (function() {
    var count;

    count = 0;

    Instrument.getID = function() {
      return count++;
    };

    function Instrument(name, kitName, pathToSound, volume) {
      var sound;
      if (volume == null) {
        volume = 50;
      }
      this._name = name.toString();
      this._kitName = kitName.toString();
      sound = soundManager.createSound({
        id: this.generateID(),
        url: pathToSound,
        autoLoad: true,
        volume: (isNumber(volume) ? volume : 50)
      });
      this._sound = sound;
    }

    Instrument.prototype.generateID = function() {
      return App.Instrument.getID();
    };

    Instrument.prototype.setName = function(name) {
      this._name = name;
      return this;
    };

    Instrument.prototype.getName = function() {
      return this._name;
    };

    Instrument.prototype.setSound = function(sound) {
      if (sound === null || (sound !== null && (sound.bytesLoaded != null))) {
        this._sound = sound;
      }
      return this;
    };

    Instrument.prototype.getSound = function() {
      return this._sound;
    };

    Instrument.prototype.serialize = function() {
      return {
        name: this._name,
        kitName: this._kitName,
        volume: this._sound.volume
      };
    };

    return Instrument;

  })();

}).call(this);
